name: relation
version: 2.0.1
description: the stream representation of the relations of the entities and widget utilities
homepage: "https://github.com/surfstudio/SurfGear/tree/main/packages/relation"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"

dependencies:
  flutter:
    sdk: flutter
  rxdart: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

flutter:
